spring:
  application:
    name: demo-transaction

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bankuser
    password: bankpass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
